Controllers/CardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.Extensions.Hosting.Internal;
using PayPal.Api;
using Seminar_1.Models;

namespace Seminar_1.Controllers
{
    [Route("[Controller]")]
    public class CardController : Controller
    {
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly Seminar1Context context;
        private IConfiguration configuration;
        private Payment payment;

        public CardController(IHttpContextAccessor httpContextAccessor, Seminar1Context context, IConfiguration configuration)
        {      
            this.httpContextAccessor = httpContextAccessor;
            this.context = context;
            this.configuration = configuration;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var prodList = context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList();
            var shopList = HttpContext.Session.Get<Dictionary<int,int>>(SessionHelper.ShoppingCart);
            if (shopList == null)
                shopList = new Dictionary<int,int>();

            var products = prodList.Where(p => shopList.ContainsKey(p.Id)).ToList();
            return View(products);
        }


        [HttpGet]
        [Route("PaymentWithPaypal")]
        public ActionResult PaymentWithPayPal(string cancel = null, string blogId = "", string payerId = "", string guid = "")
        {
            var clientId = configuration.GetValue<string>("PayPal:Key");
            var clientSecret = configuration.GetValue<string>("PayPal:Secret");
            var mode = configuration.GetValue<string>("PayPal:mode");
            var apiContext = PayPalConfiguration.GetAPIContext(clientId, clientSecret, mode);

            try
            {
                if (string.IsNullOrWhiteSpace(payerId))
                {
                    var baseURI = this.Request.Scheme + "://" + this.Request.Host + "/Card/PaymentWithPayPal?";
                    var guidd = Convert.ToString((new Random()).Next(100000));
                    guid = guidd;

                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid, blogId);
                    var links = createdPayment.links.GetEnumerator();
                    string? paypalRedirectUrl = null;
                    while(links.MoveNext())
                    {
                        var lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            paypalRedirectUrl = lnk.href;
                        }
                    }

                    httpContextAccessor.HttpContext.Session.SetString("payment", createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    var paymentId = httpContextAccessor.HttpContext.Session.GetString("payment");
                    var executedPayment = ExecutePayment(apiContext, payerId, paymentId);
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("PaymentFailed");
                    }

                    var blogs = executedPayment.transactions[0].item_list.items[0].sku;

                    // empty the bag
                    var shopList = new Dictionary<int,int>();
                    HttpContext.Session.Set(SessionHelper.ShoppingCart, shopList);

                    return View("PaymentSuccess");
                }
            }
            catch(Exception e)
            {
                return View("PaymentFailed");
            }
        }

        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            { payer_id = payerId,
            };

            this.payment = new Payment()
            {
                id = paymentId,
            };

            return this.payment.Execute(apiContext, paymentExecution);
        }

        private Payment CreatePayment(APIContext apiContext, string redirectUrl, string blogId)
        {
            var itemList = new ItemList()
            {
                items = new List<Item>()
            };

            var prodList = context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList();
            var shopList = HttpContext.Session.Get<Dictionary<int,int>>(SessionHelper.ShoppingCart);
            var prodsInBag = prodList.Where(p => shopList.ContainsKey(p.Id)).ToList();

            decimal totalAmount = 0;

            foreach(var prod in prodsInBag)
            {
                itemList.items.Add(new Item()
                {
                    name = prod.Name,
                    currency = "EUR",
                    price = string.Format("{0}", prod.Price),
                    quantity = string.Format("{0}", shopList[prod.Id]),
                    sku = "asd"
                });

                totalAmount += prod.Price * shopList[prod.Id];
            }

            var payer = new Payer()
            {
                payment_method = "paypal"
            };

            var redirectUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };

            var amount = new Amount()
            {
                currency = "EUR",
                total = string.Format("{0}", totalAmount)
            };

            var tramsactionList = new List<Transaction>();

            tramsactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = Guid.NewGuid().ToString(),
                amount = amount,
                item_list = itemList
            });

            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = tramsactionList,
                redirect_urls = redirectUrls
            };

            return this.payment.Create(apiContext);
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Seminar_1.Models;
using System.Security.Claims;
using System.Text;

namespace Seminar_1.Controllers
{
    public class LoginController : Controller
    {
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly Seminar1Context context;

        public LoginController(IWebHostEnvironment hostEnvironment, Seminar1Context context)
        {
            this.hostEnvironment = hostEnvironment;
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new LoginVM());
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVM loginVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(loginVM);
            }

            var users = context.Users.ToList();
            var user = users.FirstOrDefault(u => u.UserName == loginVM.UserName);

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid Credentials");
                return View(loginVM);
            }

            if (user.Password != hashPass(loginVM.Password))
            {
                ModelState.AddModelError(string.Empty, "Invalid Credentials");
                return View(loginVM);
            }

            List<Claim> claims = new List<Claim>()
            {
                new Claim("UserName", loginVM.UserName),
            };

            ClaimsIdentity claimsIdentity= new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = false,
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        string hashPass(string password)
        {
            string hashed = Convert.ToBase64String(Encoding.ASCII.GetBytes(password));
            //Console.WriteLine($"HAshed password: {hashed}");
            return hashed;
        }

    }
}

Controllers/RegisterController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Seminar_1.Models;
using System.Text;



namespace Seminar_1.Controllers
{
    [Route("[Controller]")]
    public class RegisterController : Controller
    {
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly Seminar1Context context;
        public RegisterController(IWebHostEnvironment hostEnvironment, Seminar1Context context)
        {
            this.hostEnvironment = hostEnvironment;
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new UserVM());
        }

        [HttpPost]
        public async Task<IActionResult> Index(UserVM userVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(userVM);
            }

            userVM.Password = hashPass(userVM.Password);
            context.Add(UserVM.VMUserToUser(userVM));
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        string hashPass(string password)
        {
            string hashed = Convert.ToBase64String(Encoding.ASCII.GetBytes(password));
            //Console.WriteLine($"HAshed password: {hashed}");
            return hashed;
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Seminar_1.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{
    var shoppingList = HttpContextAccessor.HttpContext.Session.Get<Dictionary<int,int>>(SessionHelper.ShoppingCart);
    var shoppingCount = 0;
    // count the items, if there is a shopping list
    if (shoppingList != null)
        foreach(var item in shoppingList) {
            shoppingCount += item.Value;
        }

    bool isUserAuth = (HttpContextAccessor.HttpContext.User != null) && (HttpContextAccessor.HttpContext.User.Identity != null) && HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated;
    var name = "";
    if (isUserAuth) {
        name = HttpContextAccessor.HttpContext.User.FindFirst("UserName").Value;
    }
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - R&G Plants</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">R&G Plants</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Plants</a>
                        </li>

                        @if (!isUserAuth)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="Register" asp-action="Index">Create Account</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="User" asp-action="Index">@name</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" sp-area="" asp-controller="Card" asp-action="Index">
                                <span class="fas fa-shopping-cart"></span> &nbsp; (@shoppingCount)</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Footer section
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/product.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>